### ISSUE TITLE
git troubles on ci/CTest2JUnit.xsl patches/hdf5-config.patch

### ISSUE THREAD

**Issue by eolivi** [openmeeg/OpenMEEG-project#3]
I cloned OpenMEEG-Project and some files appear as having local modifications
	modifié :         ci/CTest2JUnit.xsl
	modifié :         patches/hdf5-config.patch
I tried twice in brand new folders but the same appear, and I've never touched these files.
Is it a problem on my local configuration or the same happens to you @papadop ?

BTW: the file ci/CTest2JUnit.xsl is also in openmeeg/ci... is the problem linked ?

thank you ;-)

**Comment by agramfort** [comment]
no idea sorry

**Comment by papadop** [comment]
I have the same problem.
Well I guess that it is because ci/CTest2JUnit.xsl is in DOS file format. Git should do something when it checkouts it. I converted it to unix file format. It should remove the problem.
For patches/hdf5-config.patch, the file is converted into unix file format at checkout (.gitattribute - but neither .patch nor .xsl is mentioned at the time of this writting and the behaviour is different). 
I wonder whether pushing the unix file format version will cause troubles when applying the patch on hdf (normally no).

In any case, this is not important and I'm not sure there is a way to make things work well for both linux and windows (but as I'm biased I will probably do what is cool for linux/MAC).


 Otherwise there are some git configs we can use...

**Comment by papadop** [comment]
I think this is now OK. Closing the issue...
